### ISSUE TITLE
java.lang.IllegalStateException in XMPPConnection.sendPacket()

### ISSUE THREAD

**Issue by GoogleCodeExporter** [baluragala/gtalksms#126]
```
java.lang.IllegalStateException: Not connected to server.
at org.jivesoftware.smack.XMPPConnection.sendPacket(XMPPConnection.java:488)
at 
com.googlecode.gtalksms.XmppManager.onConnectionComplete(XmppManager.java:409)
at com.googlecode.gtalksms.XmppManager.initConnection(XmppManager.java:370)
at com.googlecode.gtalksms.XmppManager.start(XmppManager.java:119)
at com.googlecode.gtalksms.XmppManager.start(XmppManager.java:113)
at 
com.googlecode.gtalksms.XmppManager.xmppRequestStateChange(XmppManager.java:170)
at com.googlecode.gtalksms.MainService.onHandleIntent(MainService.java:191)
at 
com.googlecode.gtalksms.MainService$ServiceHandler.handleMessage(MainService.jav
a:94)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:123)
at android.os.HandlerThread.run(HandlerThread.java:60)

on Nexus One GTalkSMS v2.0
```

Original issue reported on code.google.com by `Florent....@gmail.com` on 11 Mar 2011 at 1:41

**Comment by GoogleCodeExporter** [comment]
```
Looks like the connection got closed just in the moment onConnectionComplete() 
was running. We now catch this exception an try to restart the connection.
See: 
http://code.google.com/p/gtalksms/source/detail?r=8519d01692437d6cde18b533cafd49
927c9cdefb
```

Original comment by `fschm...@gmail.com` on 11 Mar 2011 at 4:52
- Changed state: **WaitingForRelease**

**Comment by GoogleCodeExporter** [comment]
```
Fixed in v2.1
```

Original comment by `Florent....@gmail.com` on 14 Mar 2011 at 10:42
- Changed state: **Fixed**

**Comment by GoogleCodeExporter** [comment]
Original comment by `fschm...@gmail.com` on 25 Aug 2011 at 7:50
- Changed state: **Deployed**

**Comment by GoogleCodeExporter** [comment]
Original comment by `fschm...@gmail.com` on 2 Oct 2011 at 10:52
- Changed title: **java.lang.IllegalStateException in XMPPConnection.sendPacket()**
- Added labels: **FromMarket**
