### ISSUE TITLE
java.lang.NullPointerException in ContextImpl.openFileOutput()

### ISSUE THREAD

**Issue by GoogleCodeExporter** [baluragala/gtalksms#128]
```
java.lang.RuntimeException: Unable to create service 
com.googlecode.gtalksms.MainService: java.lang.NullPointerException
at android.app.ActivityThread.handleCreateService(ActivityThread.java:2969)
at android.app.ActivityThread.access$3300(ActivityThread.java:125)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2087)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:123)
at android.app.ActivityThread.main(ActivityThread.java:4627)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:521)
at 
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:861)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:619)
at dalvik.system.NativeStart.main(Native Method)
Caused by: java.lang.NullPointerException
at android.app.ContextImpl.openFileOutput(ContextImpl.java:475)
at android.content.ContextWrapper.openFileOutput(ContextWrapper.java:158)
at 
com.googlecode.gtalksms.tools.GoogleAnalyticsHelper.createDatefile(GoogleAnalyti
csHelper.java:145)
at 
com.googlecode.gtalksms.tools.GoogleAnalyticsHelper.datefileHasCurrentDate(Googl
eAnalyticsHelper.java:139)
at 
com.googlecode.gtalksms.tools.GoogleAnalyticsHelper.trackServiceStartsPerDay(Goo
gleAnalyticsHelper.java:105)
at com.googlecode.gtalksms.MainService.onCreate(MainService.java:299)
at android.app.ActivityThread.handleCreateService(ActivityThread.java:2959)
... 10 more

in GTalkSMS v2.0

```

Original issue reported on code.google.com by `Florent....@gmail.com` on 14 Mar 2011 at 10:50

**Comment by GoogleCodeExporter** [comment]
Original comment by `Florent....@gmail.com` on 14 Mar 2011 at 8:31
- Changed state: **WaitingForRelease**

**Comment by GoogleCodeExporter** [comment]
```
Fixed in v2.1
```

Original comment by `Florent....@gmail.com` on 14 Mar 2011 at 10:42
- Changed state: **Fixed**

**Comment by GoogleCodeExporter** [comment]
Original comment by `fschm...@gmail.com` on 25 Aug 2011 at 7:50
- Changed state: **Deployed**

**Comment by GoogleCodeExporter** [comment]
Original comment by `fschm...@gmail.com` on 2 Oct 2011 at 10:52
- Changed title: **java.lang.NullPointerException in ContextImpl.openFileOutput()**
- Added labels: **FromMarket**
