### ISSUE TITLE
Some commands result in a "unknown command" error message.

### ISSUE THREAD

**Issue by GoogleCodeExporter** [baluragala/gtalksms#132]
```
What steps will reproduce the problem?
1.Sending ? in all possible way from my client and from my phones internal 
GTalk.


What is the expected output?
1.List of commands


What do you see instead?
"'?': unknown command. Send "?" for get help." 


Additional informations:
GTalkSMS version =2.1.1
Android OS version =2.3.3 Build GRI40
Phone model =Google Nexus One US mod.

Things i have tested:
Change my keyboard lang. from native Swedish to eng/US. Same answer.

Using both trilian/digsby/webgtalt/gtalk app. Same answer.

Had tested with and without "".

Logg:
03-28 07:28:35.247 I/gtalksms( 9018): onCommandReceived(): ?
03-28 07:28:35.257 I/gtalksms( 9018): Sending message "'?': unknown command..." 
to 
03-28 07:28:35.267 I/gtalksms( 9018): handled action 
'com.googlecode.gtalksms.action.XMPP.MESSAGE_RECEIVED' - state now 2


```

Original issue reported on code.google.com by `James.R....@gmail.com` on 28 Mar 2011 at 5:58

**Comment by GoogleCodeExporter** [comment]
```
Now thats what I call *strange*. The log locks fine (e.g. no hidden whitespace) 
and I am unable to reproduce this with 2.1.1. :(
Does "help" work? Do the other commands work?
```

Original comment by `fschm...@gmail.com` on 28 Mar 2011 at 8:43

**Comment by GoogleCodeExporter** [comment]
```
No, have tried most of the commands I know in linux / dos environment.
```

Original comment by `James.R....@gmail.com` on 28 Mar 2011 at 8:50

**Comment by GoogleCodeExporter** [comment]
```
Do you update GTalkSMS or it's the first time that you use it ?

If it's an update try to uninstall and reinstall the application.
If it's the first time that you use the application, check the "Address to 
notify" parameter in "Connection settings".
```

Original comment by `Florent....@gmail.com` on 28 Mar 2011 at 9:49

**Comment by GoogleCodeExporter** [comment]
```
You could also try to kill the GTalkSMS Service first. Then restart/reconnect 
GTalkSMS and see if the ? command is still unknown.
I just encountered this behavior: Looks like we have a program path which ends 
in the CONNECTED state where the _commands map is not setup accordingly.
```

Original comment by `fschm...@gmail.com` on 28 Mar 2011 at 12:33
- Changed title: **Every command results in a "unknown command" error message.**
- Changed state: **Accepted**

**Comment by GoogleCodeExporter** [comment]
```
Ok, now its working. I restart the nexus one and then it worked :). Yes, it's 
my first try with gtalksms. Never inst. before. 
```

Original comment by `James.R....@gmail.com` on 28 Mar 2011 at 6:17

**Comment by GoogleCodeExporter** [comment]
```
But it's not every command thats give unknown. Some worked like "where" and 
"ring"
```

Original comment by `James.R....@gmail.com` on 28 Mar 2011 at 6:21

**Comment by GoogleCodeExporter** [comment]
```
I'm on a desire and it's the same for me here since last version (but i also 
upgraded my os, CyanogenMod7 from rc2 to rc3 then rc4 within the same days ...)
"sms", "reply" and "?" are not working although "copy" is
I reverted back to one of my backup on 1.9 and it worked again then stopped 
working with market upgrade ...
```

Original comment by `yoanjacq...@gmail.com` on 31 Mar 2011 at 4:08

**Comment by GoogleCodeExporter** [comment]
```
This same thing happened to me today. Once I restarted my phone it all worked. 
Weird. I'm on an HTC Glacier.
```

Original comment by `John.Kee...@gmail.com` on 31 Mar 2011 at 5:04

**Comment by GoogleCodeExporter** [comment]
```
same thing happened to me several times on my Nexus S (Cyanogenmod 7). It seems 
that it happens mostly after the phone switch in and out of Wifi a lot, but I'm 
not sure if it's really the cause or not.
```

Original comment by `dangsqu...@gmail.com` on 31 Mar 2011 at 7:34

**Comment by GoogleCodeExporter** [comment]
```
Thanks for your reports! 
Can you confirm that killing and restarting GTalkSMS solves this issue? Does 
this happen sometimes or every time you use version >= 2.1?
I also assume that it has something to do with frequent reconnects of the data 
connection (3G/Wifi/etc).
```

Original comment by `fschm...@gmail.com` on 31 Mar 2011 at 8:53
- Changed title: **Some commands result in a "unknown command" error message.**
- Added labels: **Priority-High**
- Removed labels: **Priority-Medium**

**Comment by GoogleCodeExporter** [comment]
```
1) no, killing the service and restrating it doesn't (always ?) solve the issue
2) it seems to happen every time after a while with versions >=2.1
3) i don't think the frequent reconnects are related in my case since I only 
activate gtalksms (via tasker) when i'm conncted to a wifi network (at home or 
at work)

```

Original comment by `yoanjacq...@gmail.com` on 1 Apr 2011 at 7:01

**Comment by GoogleCodeExporter** [comment]
```
Although rebooting the phone does the trick for now, i'll update if anyhting 
goes wrong during the day !
```

Original comment by `yoanjacq...@gmail.com` on 1 Apr 2011 at 7:24

**Comment by GoogleCodeExporter** [comment]
```
Hi ! Same here, since v2.1 I can't send any command through Gmail, always the 
same answer than above. Rebooting the phone did the trick today. As I don't 
shut the phone down usually, I can't say if it's always working.

I'm always using it through 3G.

Nexus One, ROM Google 2.3.3 (GRI40)
```

Original comment by `Guillaum...@gmail.com` on 1 Apr 2011 at 11:28

**Comment by GoogleCodeExporter** [comment]
```
Be sure to restart GTalkSMS completely, e.g. killing the service will not kill 
the whole process on android if there is still an Activity or View, like the 
MainScreen, open or as background View active.
The "Program Manager" from Samsung on the Galaxy S seems to do the job right. A 
reboot should not be necessary, as killing the *whole* process should solve the 
problem at least temporary.
```

Original comment by `fschm...@gmail.com` on 1 Apr 2011 at 12:28

**Comment by GoogleCodeExporter** [comment]
```
I get the problem, too (2.1.1), with the following log message:

    04-03 14:36:09.207 E/gtalksms(24938): MainService.setupListenersForConnection: Setup commands error java.lang.NullPointerException
    04-03 14:36:09.227 E/gtalksms(24938): java.lang.NullPointerException
    04-03 14:36:09.227 E/gtalksms(24938): at com.googlecode.gtalksms.cmd.FileCmd.<init>(FileCmd.java:27)
    04-03 14:36:09.227 E/gtalksms(24938): at com.googlecode.gtalksms.MainService.setupCommands(MainService.java:618)
    04-03 14:36:09.227 E/gtalksms(24938): at com.googlecode.gtalksms.MainService.setupListenersForConnection(MainService.java:684)
    04-03 14:36:09.227 E/gtalksms(24938): at com.googlecode.gtalksms.MainService.updateListenersToCurrentState(MainService.java:668)
    04-03 14:36:09.227 E/gtalksms(24938): at com.googlecode.gtalksms.MainService.onHandleIntent(MainService.java:151)
    04-03 14:36:09.227 E/gtalksms(24938): at com.googlecode.gtalksms.MainService$ServiceHandler.handleMessage(MainService.java:116)
    04-03 14:36:09.227 E/gtalksms(24938): at android.os.Handler.dispatchMessage(Handler.java:99)
    04-03 14:36:09.227 E/gtalksms(24938): at android.os.Looper.loop(Looper.java:123)
    04-03 14:36:09.227 E/gtalksms(24938): at android.os.HandlerThread.run(HandlerThread.java:60)
```

Original comment by `Eckankar` on 3 Apr 2011 at 12:43

**Comment by GoogleCodeExporter** [comment]
```
thanks to your log I'll fix this issue.
I hope that it is the only case.
```

Original comment by `Florent....@gmail.com` on 3 Apr 2011 at 7:24
- Changed state: **Started**

**Comment by GoogleCodeExporter** [comment]
Original comment by `Florent....@gmail.com` on 3 Apr 2011 at 8:41
- Changed state: **WaitingForRelease**

**Comment by GoogleCodeExporter** [comment]
```
Fixed in v2.1.2
```

Original comment by `Florent....@gmail.com` on 3 Apr 2011 at 8:48
- Changed state: **Fixed**

**Comment by GoogleCodeExporter** [comment]
```
I just found a bug with the new version that is related to this bug. Now, 
instead of showing unknown command, GTalkSMS doesn't show anything at all. 
ring, where and stop still work. Part of the debug log that is relevant:

04-04 18:26:32.072 I/gtalksms(30992): XMPP Packet received - but without body 
(body == null)
04-04 18:26:33.253 I/gtalksms(30992): XMPP packet received - sending Intent: 
com.googlecode.gtalksms.action.XMPP.MESSAGE_RECEIVED
04-04 18:26:33.272 I/gtalksms(30992): onStartCommand(): Intent 
com.googlecode.gtalksms.action.XMPP.MESSAGE_RECEIVED
04-04 18:26:33.274 I/gtalksms(30992): handling action 
'com.googlecode.gtalksms.action.XMPP.MESSAGE_RECEIVED' while in state 2
04-04 18:26:33.276 I/gtalksms(30992): onCommandReceived(): "help"
04-04 18:26:33.276 I/gtalksms(30992): executeCommand: _commands.size=30
04-04 18:26:33.311 E/gtalksms(30992): MainService send XmppMsg: _xmppMgr == null
04-04 18:26:33.312 I/gtalksms(30992): handled action 
'com.googlecode.gtalksms.action.XMPP.MESSAGE_RECEIVED' - state now 2
04-04 18:26:37.243 I/gtalksms(30992): XMPP Packet received - but without body 
(body == null)
04-04 18:26:37.286 I/gtalksms(30992): XMPP packet received - sending Intent: 
com.googlecode.gtalksms.action.XMPP.MESSAGE_RECEIVED
04-04 18:26:37.309 I/gtalksms(30992): onStartCommand(): Intent 
com.googlecode.gtalksms.action.XMPP.MESSAGE_RECEIVED
04-04 18:26:37.311 I/gtalksms(30992): handling action 
'com.googlecode.gtalksms.action.XMPP.MESSAGE_RECEIVED' while in state 2
04-04 18:26:37.311 I/gtalksms(30992): onCommandReceived(): "?"
04-04 18:26:37.311 I/gtalksms(30992): executeCommand: _commands.size=30
04-04 18:26:37.327 E/gtalksms(30992): MainService send XmppMsg: _xmppMgr == null
04-04 18:26:37.327 I/gtalksms(30992): handled action 
'com.googlecode.gtalksms.action.XMPP.MESSAGE_RECEIVED' - state now 2
```

Original comment by `dangsqu...@gmail.com` on 4 Apr 2011 at 10:29

**Comment by GoogleCodeExporter** [comment]
```
It seems to have fixed it on my phone...
```

Original comment by `yoanjacq...@gmail.com` on 5 Apr 2011 at 7:36

**Comment by GoogleCodeExporter** [comment]
Original comment by `fschm...@gmail.com` on 25 Aug 2011 at 7:50
- Changed state: **Deployed**
