### ISSUE TITLE
NullPointerException in MultiChat

### ISSUE THREAD

**Issue by GoogleCodeExporter** [baluragala/gtalksms#136]
```
It's happen on every SMS
TODO : manage this error

java.lang.NullPointerException
at org.jivesoftware.smackx.muc.MultiUserChat.init(MultiUserChat.java:2221)
at org.jivesoftware.smackx.muc.MultiUserChat.<init>(MultiUserChat.java:159)
at com.googlecode.gtalksms.xmpp.XmppMuc.createRoom(XmppMuc.java:185)
at com.googlecode.gtalksms.xmpp.XmppMuc.writeRoom(XmppMuc.java:69)
at com.googlecode.gtalksms.MainService.onHandleIntent(MainService.java:201)
at 
com.googlecode.gtalksms.MainService$ServiceHandler.handleMessage(MainService.jav
a:116)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:123)
at android.os.HandlerThread.run(HandlerThread.java:60)
```

Original issue reported on code.google.com by `Florent....@gmail.com` on 5 Apr 2011 at 2:56

**Comment by GoogleCodeExporter** [comment]
```
Exception (NPE) != XmppException

We need to wrap lines 185-186 in XmppMuc in an new try-catch block which throws 
this exception back wrapped in an XmppException to the calling method.
```

Original comment by `fschm...@gmail.com` on 5 Apr 2011 at 3:15

**Comment by GoogleCodeExporter** [comment]
```
We just need to replace XmppException by Exception in MainService:201

We have to catch all exception and use the other method to show SMS
```

Original comment by `Florent....@gmail.com` on 5 Apr 2011 at 3:30

**Comment by GoogleCodeExporter** [comment]
Original comment by `fschm...@gmail.com` on 6 Apr 2011 at 8:27
- Changed state: **WaitingForRelease**

**Comment by GoogleCodeExporter** [comment]
```
Fixed in v2.1.3
```

Original comment by `Florent....@gmail.com` on 6 Apr 2011 at 9:34
- Changed state: **Fixed**

**Comment by GoogleCodeExporter** [comment]
Original comment by `fschm...@gmail.com` on 25 Aug 2011 at 7:50
- Changed state: **Deployed**

**Comment by GoogleCodeExporter** [comment]
Original comment by `fschm...@gmail.com` on 2 Oct 2011 at 10:52
- Changed title: **NullPointerException in MultiChat**
- Added labels: **FromMarket**
