### ISSUE TITLE
ArrayIndexOutOfBoundsException in SMSHelper.setSentIntentTrue()

### ISSUE THREAD

**Issue by GoogleCodeExporter** [baluragala/gtalksms#187]
```
v2.2.4

java.lang.RuntimeException: Error receiving broadcast Intent { 
act=com.googlecode.gtalksms.action.SMS_SENT (has extras) } in 
com.googlecode.gtalksms.cmd.smsCmd.SentIntentReceiver@4074b200
at android.app.LoadedApk$ReceiverDispatcher$Args.run(LoadedApk.java:722)
at android.os.Handler.handleCallback(Handler.java:587)
at android.os.Handler.dispatchMessage(Handler.java:92)
at android.os.Looper.loop(Looper.java:123)
at android.app.ActivityThread.main(ActivityThread.java:3835)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:507)
at 
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:841)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:599)
at dalvik.system.NativeStart.main(Native Method)
Caused by: java.lang.ArrayIndexOutOfBoundsException
at 
com.googlecode.gtalksms.databases.SMSHelper.setSentIntentTrue(SMSHelper.java:81)
at 
com.googlecode.gtalksms.cmd.smsCmd.SentIntentReceiver.onReceiveWithSms(SentInten
tReceiver.java:24)
at 
com.googlecode.gtalksms.cmd.smsCmd.SmsPendingIntentReceiver.onReceive(SmsPending
IntentReceiver.java:34)
at android.app.LoadedApk$ReceiverDispatcher$Args.run(LoadedApk.java:709)
... 9 more

```

Original issue reported on code.google.com by `Florent....@gmail.com` on 16 Jun 2011 at 12:11

**Comment by GoogleCodeExporter** [comment]
Original comment by `Florent....@gmail.com` on 9 Jul 2011 at 11:00

**Comment by GoogleCodeExporter** [comment]
Original comment by `fschm...@gmail.com` on 25 Aug 2011 at 8:52
- Changed state: **Fixed**

**Comment by GoogleCodeExporter** [comment]
```
Fixed in version 3.2
```

Original comment by `Florent....@gmail.com` on 28 Aug 2011 at 3:46
- Changed state: **Deployed**

**Comment by GoogleCodeExporter** [comment]
```
Issue 224 has been merged into this issue.
```

Original comment by `fschm...@gmail.com` on 2 Oct 2011 at 10:51

**Comment by GoogleCodeExporter** [comment]
Original comment by `fschm...@gmail.com` on 2 Oct 2011 at 10:53
- Changed title: **ArrayIndexOutOfBoundsException in SMSHelper.setSentIntentTrue()**
- Added labels: **FromMarket**
