### ISSUE TITLE
Exception when sending long text messages

### ISSUE THREAD

**Issue by GoogleCodeExporter** [baluragala/gtalksms#341]
```
This error appears when sending long messages with the command sms:

E/gtalksms( 1391): executeCommand() Exception
E/gtalksms( 1391): java.lang.NullPointerException: collection == null
E/gtalksms( 1391):  at android.os.Parcel.readException(Parcel.java:1437)
E/gtalksms( 1391):  at android.os.Parcel.readException(Parcel.java:1385)
E/gtalksms( 1391):  at 
com.android.internal.telephony.ISms$Stub$Proxy.sendMultipartText(ISms.java:631)
E/gtalksms( 1391):  at 
android.telephony.SmsManager.sendMultipartTextMessage(SmsManager.java:214)
E/gtalksms( 1391):  at 
com.googlecode.gtalksms.cmd.SmsCmd.sendSMSByPhoneNumber(SmsCmd.java:491)
E/gtalksms( 1391):  at 
com.googlecode.gtalksms.cmd.SmsCmd.sendSMS(SmsCmd.java:312)
E/gtalksms( 1391):  at 
com.googlecode.gtalksms.cmd.SmsCmd.execute(SmsCmd.java:108)
E/gtalksms( 1391):  at 
com.googlecode.gtalksms.cmd.CommandHandlerBase.execute(CommandHandlerBase.java:2
31)
E/gtalksms( 1391):  at 
com.googlecode.gtalksms.MainService.executeCommand(MainService.java:597)
E/gtalksms( 1391):  at 
com.googlecode.gtalksms.MainService.handleCommandFromXMPP(MainService.java:729)
E/gtalksms( 1391):  at 
com.googlecode.gtalksms.MainService.onHandleIntent(MainService.java:256)
E/gtalksms( 1391):  at 
com.googlecode.gtalksms.MainService$ServiceHandler.handleMessage(MainService.jav
a:151)
E/gtalksms( 1391):  at android.os.Handler.dispatchMessage(Handler.java:99)
E/gtalksms( 1391):  at android.os.Looper.loop(Looper.java:137)
E/gtalksms( 1391):  at android.os.HandlerThread.run(HandlerThread.java:61)

The error only appears when the setting "Notification Settings" > "SMS sent" is 
not enabled

```

Original issue reported on code.google.com by `Florent....@gmail.com` on 10 Nov 2013 at 11:07

**Comment by GoogleCodeExporter** [comment]
```
Fixed in 4.4.4.74
```

Original comment by `Florent....@gmail.com` on 10 Nov 2013 at 11:19
- Changed state: **FixedInBeta**

**Comment by GoogleCodeExporter** [comment]
```
4.4.4.75 deployed in production
```

Original comment by `Florent....@gmail.com` on 20 Nov 2013 at 4:48
- Changed state: **Deployed**

**Comment by GoogleCodeExporter** [comment]
```
Thanks for fixing this. Would you be open to explaining the code changes as we 
are facing similar issues with our users?

thanking in advance!
```

Original comment by `alanrock...@gmail.com` on 8 Jan 2014 at 6:13

**Comment by GoogleCodeExporter** [comment]
```
Please check the changset 
https://code.google.com/p/gtalksms/source/detail?r=c12f71d78a44e3fb3d5b58ecc8e1b
ea1566ea093
and the file /src/com/googlecode/gtalksms/cmd/SmsCmd.java
```

Original comment by `Florent....@gmail.com` on 9 Jan 2014 at 10:56
