### ISSUE TITLE
Hiding apps sometimes duplicates existing filters

### ISSUE THREAD

**Issue by GoogleCodeExporter** [baluragala/gtalksms#356]
```
With data cleared, I tried to hide some apps. At some point, suddenly existing 
filters get duplicated:

07:30 <The-Compiler> notif:hide:app:AFWall+ 
[...]
07:30 <The-Compiler> notif:hide:app:Orbot
07:30 <The-Compiler> notif:hide:app:OsmAnd+  
07:30 <The-Compiler> notif:hide:app:Package installer
[...]
07:30 <The-Compiler> notif:hide:app:ÖBB Tickets

At first, everything works like expected:

07:30 <phone> Applications blacklist: GTalkSMS, AFWall+
07:30 <phone> Messages blacklist:   
[...]
07:31 <phone> Applications blacklist: GTalkSMS, AFWall+, Android System, Clock, 
DSub, Dialer, Dolphin Browser, Download Manager, Firefox, Google Play Store, 
JuiceSSH, K-9 Mail, Messaging, OpenDelta, Orbot

Now when blocking OsmAnd+, suddenly everything duplicates:

07:31 <phone> Messages blacklist:   
07:31 <phone> Applications blacklist: GTalkSMS, AFWall+, Android System, Clock, 
DSub, Dialer, Dolphin Browser, Download Manager, Firefox, Google Play Store, 
JuiceSSH, K-9 Mail, Messaging, OpenDelta, Orbot, GTalkSMS, AFWall+, Android 
System, Clock, DSub, Dialer, Dolphin Browser, Download Manager, Firefox, Google 
Play Store, JuiceSSH, K-9 Mail, Messaging, OpenDelta, Orbot, OsmAnd+ 

and it gets worse and worse, until (after running everything):

07:32 <phone> Applications blacklist: GTalkSMS, AFWall+, Android System, Clock, 
DSub, Dialer, Dolphin Browser, Download Manager, Firefox, Google Play Store, 
JuiceSSH, K-9 Mail, Messaging, OpenDelta, Orbot, GTalkSMS, AFWall+, Android 
System, Clock, DSub, Dialer, Dolphin Browser, Download Manager, Firefox, Google 
Play Store, JuiceSSH, K-9 Mail, Messaging, OpenDelta, Orbot, OsmAnd+, Package 
installer, Phone, RedPhone, Sleep, SuperGenPass, GTalkSMS, AFWall+, Android 
System, Clock, DSub, Dialer, Dolphin Browser, Download Manager, Firefox, Google 
Play Store, GTalkSMS, AFWall+, Android System, Clock, DSub, Dialer, Dolphin 
Browser, Download Manager, Firefox, Google Play Store, JuiceSSH, K-9 Mail, 
Messaging, OpenDelta, Orbot, GTalkSMS, AFWall+, Android System, Clock, DSub, 
Dialer, Dolphin Browser, Download Manager, Firefox, Google Play Store, 
JuiceSSH, K-9 Mail, Messaging, OpenDelta, Orbot, OsmAnd+, Package installer, 
Phone, RedPhone, Sleep, SuperGenPass, GTalkSMS, AFWall+, Android System, Clock, 
DSub, Dialer, Dolphin Browser, Download Manager, Firefox, Google Play Store, 
JuiceSSH, K-9 Mail, Messaging, OpenDelta, Orbot, GTalkSMS, AFWall+, Android 
System, Clock, DSub, Dialer, Dolphin Browser, Download Manager, Firefox, Google 
Play Store, JuiceSSH, K-9 Mail, Messaging, OpenDelta, Orbot, GTalkSMS, AFWall+, 
Android System, Clock, DSub, Dialer, Dolphin Browser, Download Manager, 
Firefox, Google Play Store, JuiceSSH, K-9 Mail, Messaging, OpenDelta, Orbot, 
OsmAnd+, Package installer, Phone, RedPhone, Sleep, SuperGenPass, Superuser, 
JuiceSSH, K-9 Mail, Messaging, OpenDelta, Orbot, OsmAnd+, Package installer, 
Phone, RedPhone, Sleep, SuperGenPass, Superuser, System Framework, System UI, 
Tasker, TextSecure, Torch, weechat (dev), ÖBB Tickets

Using GTalkSMS 4.4.4 on Android 4.4.2 with OmniRom on a HTC One GSM. I got this 
in the logs once when doing notif:show, not sure if it's related:

  4988               gtalksms  E  Failed to notified listener.
  4988               gtalksms  E  android.view.ViewRootImpl$CalledFromWrongThreadException: Only the original thread that created a view hierarchy can touch its views.
  4988               gtalksms  E    at android.view.ViewRootImpl.checkThread(ViewRootImpl.java:6094)
  4988               gtalksms  E    at android.view.ViewRootImpl.invalidateChildInParent(ViewRootImpl.java:857)
  4988               gtalksms  E    at android.view.ViewGroup.invalidateChild(ViewGroup.java:4320)
  4988               gtalksms  E    at android.view.View.invalidate(View.java:10885)
  4988               gtalksms  E    at android.widget.TextView.invalidateRegion(TextView.java:4651)
  4988               gtalksms  E    at android.widget.TextView.invalidateCursor(TextView.java:4594)
  4988               gtalksms  E    at android.widget.TextView.spanChange(TextView.java:7502)
  4988               gtalksms  E    at android.widget.TextView$ChangeWatcher.onSpanAdded(TextView.java:9210)
  4988               gtalksms  E    at android.text.SpannableStringBuilder.sendSpanAdded(SpannableStringBuilder.java:979)
  4988               gtalksms  E    at android.text.SpannableStringBuilder.setSpan(SpannableStringBuilder.java:688)
  4988               gtalksms  E    at android.text.SpannableStringBuilder.setSpan(SpannableStringBuilder.java:588)
  4988               gtalksms  E    at android.text.Selection.setSelection(Selection.java:76)
  4988               gtalksms  E    at android.text.Selection.setSelection(Selection.java:87)
  4988               gtalksms  E    at android.text.method.ArrowKeyMovementMethod.initialize(ArrowKeyMovementMethod.java:302)
  4988               gtalksms  E    at android.widget.TextView.setText(TextView.java:3801)
  4988               gtalksms  E    at android.widget.TextView.setText(TextView.java:3671)
  4988               gtalksms  E    at android.widget.EditText.setText(EditText.java:80)
  4988               gtalksms  E    at android.widget.TextView.setText(TextView.java:3646)
  4988               gtalksms  E    at com.googlecode.gtalksms.panels.tabs.ConnectionTabFragment$1.OnSettingChanged(ConnectionTabFragment.java:45)
  4988               gtalksms  E    at com.googlecode.gtalksms.SettingsManager.OnPreferencesUpdated(SettingsManager.java:300)
  4988               gtalksms  E    at com.googlecode.gtalksms.SettingsManager.saveSetting(SettingsManager.java:262)
  4988               gtalksms  E    at com.googlecode.gtalksms.tools.ArrayStringSetting.set(ArrayStringSetting.java:44)
  4988               gtalksms  E    at com.googlecode.gtalksms.tools.ArrayStringSetting.remove(ArrayStringSetting.java:77)
  4988               gtalksms  E    at com.googlecode.gtalksms.cmd.NotificationsCmd.execute(NotificationsCmd.java:45)
  4988               gtalksms  E    at com.googlecode.gtalksms.cmd.CommandHandlerBase.execute(CommandHandlerBase.java:229)
  4988               gtalksms  E    at com.googlecode.gtalksms.MainService.executeCommand(MainService.java:597)
  4988               gtalksms  E    at com.googlecode.gtalksms.MainService.handleCommandFromXMPP(MainService.java:729)
  4988               gtalksms  E    at com.googlecode.gtalksms.MainService.onHandleIntent(MainService.java:256)
  4988               gtalksms  E    at com.googlecode.gtalksms.MainService$ServiceHandler.handleMessage(MainService.java:151)
  4988               gtalksms  E    at android.os.Handler.dispatchMessage(Handler.java:102)
  4988               gtalksms  E    at android.os.Looper.loop(Looper.java:136)
  4988               gtalksms  E    at android.os.HandlerThread.run(HandlerThread.java:61)
  1793   MethodManagerService  W  Starting input on non-focused client com.android.internal.view.IInputMethodClient$Stub$Proxy@41e9dd20 (uid=10082 pid=4988)
```

Original issue reported on code.google.com by `m...@the-compiler.org` on 8 Apr 2014 at 5:47

**Comment by GoogleCodeExporter** [comment]
```
Hello,

The duplication might be related to the special characters as + or Ö.
I will run some tests.
```

Original comment by `Florent....@gmail.com` on 15 Apr 2014 at 7:55
- Changed state: **Accepted**

**Comment by GoogleCodeExporter** [comment]
```
same here. 

Android 4.4 stock on samsung Galaxy Note 2

bellow an exemple of my list of exception with special caracters: 
notif:hide:app:SMSBackup+
notif:hide:app:BuyMeaPie!
notif:hide:app:Téléphone
notif:hide:app:Gestionnairedetél.
```

Original comment by `Sperenz55` on 8 Jan 2015 at 2:41

**Comment by GoogleCodeExporter** [comment]
```
Any update on this? By now, when I want to add a new application to the list, I 
get spammed by over 200 lines of output...
```

Original comment by `m...@the-compiler.org` on 9 Mar 2015 at 10:36

**Comment by GoogleCodeExporter** [comment]
```
This issue was closed by revision cd24b36b1791.
```

Original comment by `yako...@gmail.com` on 1 May 2015 at 5:44
- Changed state: **Fixed**
