### ISSUE TITLE
no connect possible - ERROR,gtalksms,GTalkSMS,[XmppManager@onConnectionEstablished:467] xmppMgr exception caught service-unavailable

### ISSUE THREAD

**Issue by GoogleCodeExporter** [baluragala/gtalksms#380]
```
What steps will reproduce the problem?
1. connect to my prosody 0.9.8 xmpp server 

What is the expected output?
expected is a normal login

What do you see instead?
login is successfull (according to the prosody log) but gtalksms show error and 
retries and so on, and so on ...

Additional informations:
GT-i9505 CM12.1 nightly 02.06.2015


Logcat show the following:
ERROR,gtalksms,GTalkSMS,[XmppManager@onConnectionEstablished:467] xmppMgr 
exception caught
service-unavailable
    at org.jivesoftware.smack.PacketCollector.nextResultOrThrow(PacketCollector.java:196)
    at org.jivesoftware.smack.PacketCollector.nextResultOrThrow(PacketCollector.java:175)
    at org.jivesoftware.smackx.disco.ServiceDiscoveryManager.discoverInfo(ServiceDiscoveryManager.java:558)
    at org.jivesoftware.smackx.disco.ServiceDiscoveryManager.discoverInfo(ServiceDiscoveryManager.java:525)
    at org.jivesoftware.smackx.disco.ServiceDiscoveryManager.supportsFeature(ServiceDiscoveryManager.java:678)
    at org.jivesoftware.smackx.offline.OfflineMessageManager.supportsFlexibleRetrieval(OfflineMessageManager.java:83)
    at com.googlecode.gtalksms.xmpp.XmppOfflineMessages.handleOfflineMessages(XmppOfflineMessages.java:24)
    at com.googlecode.gtalksms.XmppManager.onConnectionEstablished(XmppManager.java:461)
    at com.googlecode.gtalksms.XmppManager.initConnection(XmppManager.java:406)
    at com.googlecode.gtalksms.XmppManager.start(XmppManager.java:185)
    at com.googlecode.gtalksms.XmppManager.xmppRequestStateChange(XmppManager.java:256)
    at com.googlecode.gtalksms.MainService.connectTransport(MainService.java:152)
    at com.googlecode.gtalksms.MainService.onHandleIntentTransportConnection(MainService.java:180)
    at com.googlecode.gtalksms.MainService$ServiceHandler.handleMessage(MainService.java:134)
    at android.os.Handler.dispatchMessage(Handler.java:102)
    at android.os.Looper.loop(Looper.java:135)
    at android.os.HandlerThread.run(HandlerThread.java:61)


If i can help more to track it down, let me know


```

Original issue reported on code.google.com by `ronny.bo...@googlemail.com` on 2 Jun 2015 at 3:45

**Comment by GoogleCodeExporter** [comment]
```
Have you enabled the off line messages handling on your server ?
```

Original comment by `Florent....@gmail.com` on 12 Jul 2015 at 3:35

**Comment by GoogleCodeExporter** [comment]
```
yes,thats enabled
```

Original comment by `ronny.bo...@googlemail.com` on 12 Jul 2015 at 3:49

**Comment by GoogleCodeExporter** [comment]
```
Can you disable it for the test?
```

Original comment by `Florent....@gmail.com` on 12 Jul 2015 at 3:53
