### ISSUE TITLE
[From Market] ContactManager uncatched exception

### ISSUE THREAD

**Issue by GoogleCodeExporter** [baluragala/gtalksms#98]
```
java.lang.NoSuchMethodError: getTypeLa"el
at 
com.googlecode.gtalksms.data.contacts.ContactsManager.getPhones(ContactsManager.
java:215)
at com.googlecode.gtalksms.cmd.ContactCmd.execute(ContactCmd.java:38)
at com.googlecode.gtalksms.MainService.onMessageReceived(MainService.java:628)
at com.googlecode.gtalksms.MainService.onHandleIntent(MainService.java:164)
at 
com.googlecode.gtalksms.MainService$ServiceHandler.handleMessage(MainService.jav
a:103)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:123)
at android.os.HandlerThread.run(HandlerThread.java:60)


version 1.9


```

Original issue reported on code.google.com by `Florent....@gmail.com` on 11 Feb 2011 at 10:18

**Comment by GoogleCodeExporter** [comment]
Original comment by `Florent....@gmail.com` on 11 Feb 2011 at 10:18
- Changed title: **[From Market] ContactManager uncatched excpetion**

**Comment by GoogleCodeExporter** [comment]
Original comment by `Florent....@gmail.com` on 11 Feb 2011 at 10:18
- Changed title: **[From Market] ContactManager uncatched exception**

**Comment by GoogleCodeExporter** [comment]
```
getTypeLabel() was introduced in API level 5, we have minSDK 5. So maybe 
someone installed on an older version somehow?
```

Original comment by `fschm...@gmail.com` on 11 Feb 2011 at 7:16

**Comment by GoogleCodeExporter** [comment]
Original comment by `Florent....@gmail.com` on 13 Feb 2011 at 3:35
- Changed state: **NotReproduced**

**Comment by GoogleCodeExporter** [comment]
Original comment by `fschm...@gmail.com` on 17 Feb 2011 at 7:05
- Changed state: **Invalid**
